srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'mem' --SEED 1111 --SAVE_NUM 41 --lora_modules 'hate-exp,meme-captions,hate-speech'
srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'mem' --SEED 1112 --SAVE_NUM 42 --lora_modules 'hate-exp,meme-captions,hate-speech'
srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'mem' --SEED 1113 --SAVE_NUM 43 --lora_modules 'hate-exp,meme-captions,hate-speech'
srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'mem' --SEED 1114 --SAVE_NUM 44 --lora_modules 'hate-exp,meme-captions,hate-speech'
srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'mem' --SEED 1115 --SAVE_NUM 45 --lora_modules 'hate-exp,meme-captions,hate-speech'

srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'harm' --SEED 1111 --SAVE_NUM 41 --lora_modules 'hate-exp,meme-captions,hate-speech'
srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'harm' --SEED 1112 --SAVE_NUM 42 --lora_modules 'hate-exp,meme-captions,hate-speech'
srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'harm' --SEED 1113 --SAVE_NUM 43 --lora_modules 'hate-exp,meme-captions,hate-speech'
srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'harm' --SEED 1114 --SAVE_NUM 44 --lora_modules 'hate-exp,meme-captions,hate-speech'
srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'harm' --SEED 1115 --SAVE_NUM 45 --lora_modules 'hate-exp,meme-captions,hate-speech'

srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'mimc' --SEED 1111 --SAVE_NUM 41 --lora_modules 'hate-exp,meme-captions,hate-speech'
srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'mimc' --SEED 1112 --SAVE_NUM 42 --lora_modules 'hate-exp,meme-captions,hate-speech'
srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'mimc' --SEED 1113 --SAVE_NUM 43 --lora_modules 'hate-exp,meme-captions,hate-speech'
srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'mimc' --SEED 1114 --SAVE_NUM 44 --lora_modules 'hate-exp,meme-captions,hate-speech'
srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'mimc' --SEED 1115 --SAVE_NUM 45 --lora_modules 'hate-exp,meme-captions,hate-speech'

srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'mem' --SEED 1111 --SAVE_NUM 51 --lora_modules 'meme-captions,hate-speech'
srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'mem' --SEED 1112 --SAVE_NUM 52 --lora_modules 'meme-captions,hate-speech'
srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'mem' --SEED 1113 --SAVE_NUM 53 --lora_modules 'meme-captions,hate-speech'
srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'mem' --SEED 1114 --SAVE_NUM 54 --lora_modules 'meme-captions,hate-speech'
srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'mem' --SEED 1115 --SAVE_NUM 55 --lora_modules 'meme-captions,hate-speech'

srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'mem' --SEED 1111 --SAVE_NUM 61 --lora_modules 'hate-exp,meme-captions'
srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'mem' --SEED 1112 --SAVE_NUM 62 --lora_modules 'hate-exp,meme-captions'
srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'mem' --SEED 1113 --SAVE_NUM 63 --lora_modules 'hate-exp,meme-captions'
srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'mem' --SEED 1114 --SAVE_NUM 64 --lora_modules 'hate-exp,meme-captions'
srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'mem' --SEED 1115 --SAVE_NUM 65 --lora_modules 'hate-exp,meme-captions'

srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'mem' --SEED 1111 --SAVE_NUM 71 --lora_modules 'hate-speech,hate-exp'
srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'mem' --SEED 1112 --SAVE_NUM 72 --lora_modules 'hate-speech,hate-exp'
srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'mem' --SEED 1113 --SAVE_NUM 73 --lora_modules 'hate-speech,hate-exp'
srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'mem' --SEED 1114 --SAVE_NUM 74 --lora_modules 'hate-speech,hate-exp'
srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'mem' --SEED 1115 --SAVE_NUM 75 --lora_modules 'hate-speech,hate-exp'

srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'harm' --SEED 1111 --SAVE_NUM 51 --lora_modules 'meme-captions,hate-speech'
srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'harm' --SEED 1112 --SAVE_NUM 52 --lora_modules 'meme-captions,hate-speech'
srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'harm' --SEED 1113 --SAVE_NUM 53 --lora_modules 'meme-captions,hate-speech'
srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'harm' --SEED 1114 --SAVE_NUM 54 --lora_modules 'meme-captions,hate-speech'
srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'harm' --SEED 1115 --SAVE_NUM 55 --lora_modules 'meme-captions,hate-speech'

srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'harm' --SEED 1111 --SAVE_NUM 61 --lora_modules 'hate-exp,meme-captions'
srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'harm' --SEED 1112 --SAVE_NUM 62 --lora_modules 'hate-exp,meme-captions'
srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'harm' --SEED 1113 --SAVE_NUM 63 --lora_modules 'hate-exp,meme-captions'
srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'harm' --SEED 1114 --SAVE_NUM 64 --lora_modules 'hate-exp,meme-captions'
srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'harm' --SEED 1115 --SAVE_NUM 65 --lora_modules 'hate-exp,meme-captions'

srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'harm' --SEED 1111 --SAVE_NUM 71 --lora_modules 'hate-speech,hate-exp'
srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'harm' --SEED 1112 --SAVE_NUM 72 --lora_modules 'hate-speech,hate-exp'
srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'harm' --SEED 1113 --SAVE_NUM 73 --lora_modules 'hate-speech,hate-exp'
srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'harm' --SEED 1114 --SAVE_NUM 74 --lora_modules 'hate-speech,hate-exp'
srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'harm' --SEED 1115 --SAVE_NUM 75 --lora_modules 'hate-speech,hate-exp'

srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'mimc' --SEED 1111 --SAVE_NUM 51 --lora_modules 'meme-captions,hate-speech'
srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'mimc' --SEED 1112 --SAVE_NUM 52 --lora_modules 'meme-captions,hate-speech'
srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'mimc' --SEED 1113 --SAVE_NUM 53 --lora_modules 'meme-captions,hate-speech'
srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'mimc' --SEED 1114 --SAVE_NUM 54 --lora_modules 'meme-captions,hate-speech'
srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'mimc' --SEED 1115 --SAVE_NUM 55 --lora_modules 'meme-captions,hate-speech'

srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'mimc' --SEED 1111 --SAVE_NUM 61 --lora_modules 'hate-exp,meme-captions'
srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'mimc' --SEED 1112 --SAVE_NUM 62 --lora_modules 'hate-exp,meme-captions'
srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'mimc' --SEED 1113 --SAVE_NUM 63 --lora_modules 'hate-exp,meme-captions'
srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'mimc' --SEED 1114 --SAVE_NUM 64 --lora_modules 'hate-exp,meme-captions'
srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'mimc' --SEED 1115 --SAVE_NUM 65 --lora_modules 'hate-exp,meme-captions'

srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'mimc' --SEED 1111 --SAVE_NUM 71 --lora_modules 'hate-speech,hate-exp'
srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'mimc' --SEED 1112 --SAVE_NUM 72 --lora_modules 'hate-speech,hate-exp'
srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'mimc' --SEED 1113 --SAVE_NUM 73 --lora_modules 'hate-speech,hate-exp'
srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'mimc' --SEED 1114 --SAVE_NUM 74 --lora_modules 'hate-speech,hate-exp'
srun --partition=researchlong  --qos=research-1-qos  python lora_composition.py --DATASET 'mimc' --SEED 1115 --SAVE_NUM 75 --lora_modules 'hate-speech,hate-exp'